### PR TITLE
[all] Ensure generic type at BaseView is a BasePresenter

### PR DESCRIPTION
**Pull request by jpventura**
Ensure generic type at `BaseView` extends `BasePresenter`.

### CODE REVIEW

**Comment by jpventura** [comment]
@JoseAlcerreca any updates on this?

**Comment by jpventura** [comment]
@florina-muntenescu, @JoseAlcerreca any updates on this?

**Comment by JoseAlcerreca** [comment]
I don't have strong feelings about it. Anyone else?

**Comment by jpventura** [comment]
@JoseAlcerreca, technically you could implement a _presenter_ that does not implement the `BasePresenter` interface and it would not violate the _presenter-view contract_.

Thus, if the method `stop` be added to `BasePresenter` (or any other change), no compilation error would be detected.

**Comment by JoseAlcerreca** [comment]
Yeah, but if the `stop` method is ever called, there would be a compilation error.

**Pull request closed without merging**
