### PR TITLE
Instantiate the ScheduleProvider at the same time the INSTANCE is declared

### PR DESCRIPTION
**Pull request by thagikura**
Since the current version of code doesn't look thread safe and I thought a null may be returned in the getInstance method.

### CODE REVIEW

**Comment by JoseAlcerreca** [comment]
What about synchronizing the getInstance() method instead? The whole point is to lazy-load the scheduler I think.

**Comment by thagikura** [comment]
Yes, synchronizing the getInstance method also works. Okay, I'll change the PR to do so.
(Sorry looks like I accidentally closed this PR. I may send another PR if I can't find a way to amend the PR)

**Comment by thagikura** [comment]
Sent another PR #178 to make the method synchronized.

**Comment by NikitaKozlov** [comment]
@thagikura why do you want to keep lazy initialisation at all? Whenever somebody access `SchedulerProvider`, the only thing he can do is call `getInstance()`. So you can just put initialisation in the field itself, put `volatile` and make it `final`.

**Comment by thagikura** [comment]
@NikitaKozlov I'm fine if the cod follows lazy initialization or not as long as thread safety is guaranteed.
Actually the first PR was instantiating the ScheduleProviders in the field itself.

So I want to follow the owner's preference regarding that point ( @JoseAlcerreca or @florina-muntenescu ?)

**Comment by NikitaKozlov** [comment]
@thagikura My point is, that even if you put initialization in the field itself, instance creation will happened only on first `getInstance()`call,  since there is no other way to interact with this class.
But it is true, it is up to owners to decide.

**Pull request closed without merging**
