### PR TITLE
[todo-mvp-rjxava] RxJava 2 migration

### PR DESCRIPTION
**Pull request by kleinsenberg**
Migrate project to RxJava 2.

### CODE REVIEW

**Comment by JoseAlcerreca** [comment]
This is why we do the version bumps :) Do you want to fix travis and circle or should I do it?

**Comment by kleinsenberg** [comment]
@JoseAlcerreca fixed 🎉

**Comment by JoseAlcerreca** [comment]
LGTM!  @florina-muntenescu haz los honores

**Comment by oldergod** [comment]
@kleinsenberg I'm trying to understand the implementation of the migration. What's the reasoning for using `Flowable` instead of `Observable` if backpressure is never managed? Is there an meaningful difference between those two?

**Pull request merged**
