### PR TITLE
Make DataSource reference in Presenter abstract

### PR DESCRIPTION
**Pull request by EfeBudak**

### CODE REVIEW

**Comment by EfeBudak** [comment]
I signed it!

**Comment by JoseAlcerreca** [comment]
We might drop the DataSource from the repository. Usually they don't share interface.

Does this only happen in the tasks presenter?

**Comment by EfeBudak** [comment]
Actually, it happens on every presenter. 
You are right, we can drop the DataSource. However, making it abstract for the presenter is more suitable for dependency inversion. The presenter does not have to know the detail of DataSource.

**Comment by JoseAlcerreca** [comment]
Well let's close this because it should be done in todo-mvp and it's a known issue. Thanks!

**Comment by savepopulation** [comment]
@JoseAlcerreca i think dropping DataSource from repository is not a proper move if you're using it also as a memory cache. It's also a data source because of providing cached data in memory.

**Comment by JoseAlcerreca** [comment]
It's not a source of data. In that case there would have to be a 'cache' DataSource, different from the repo.

**Pull request closed without merging**
