### PR TITLE
Prevent NullPointerException in ActionBar

### PR DESCRIPTION
**Pull request by Rainer-Lang**

### CODE REVIEW

**Comment by Rainer-Lang** [comment]
I signed it!

**Comment by JoseAlcerreca** [comment]
If you have seen this happening please specify in which circumstances. Also, silently checking for this null and not throwing an error or logging doesn't seem like a good idea to me.

**Comment by JoseAlcerreca** [comment]
Ping!

**Comment by Rainer-Lang** [comment]
@JoseAlcerreca I didn't "see" it in your samples. I think NPE should be prevented whereever possible.
You're right only a silent check isn't good - especially for a "blueprint" like these samples.
This NPE could happen (maybe not here but if the blueprint is used from devs) and I think we should care about this fact.

**Comment by JoseAlcerreca** [comment]
Since you agree on the disadvantages of the silent check, I'll close this PR now. Thanks!

**Pull request closed without merging**
