### PR TITLE
Added content description for navigate up

### PR DESCRIPTION
**Pull request by fisache**
Hi, while testing on androidTest, I got some problems.
In _TasksScreenTest_, occurred four errors.
all of errors are same cause, 

'_No views in hierarchy found matching: with content description: is "Navigate up"_'.
So, I added content description 'Navigate up' in navigate up or home view.

Thank you! :)

### CODE REVIEW

**Comment by fisache** [comment]
I signed it!

**Comment by fisache** [comment]
added minor typo in statistics_act.xml for graphical layout

thanks

**Comment by JoseAlcerreca** [comment]
Hi fisache,

Thanks for your PR. The solution had to be a bit more generic, so it's been fixed in https://github.com/googlesamples/android-architecture/commit/9ad2a5db47dca0e861a15a39df847213df050996

Can you check that it works for you?

Thank you!

**Comment by fisache** [comment]
Yes, Thx! 👍

**Pull request closed without merging**
