### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by dennis-sheil**

### CODE REVIEW

**Comment by dennis-sheil** [comment]
I signed the Google CLA.

**Comment by JoseAlcerreca** [comment]
For some reason github is not showing the typo.

**Comment by oldergod** [comment]
@JoseAlcerreca  here it is: "To ensure the focus **in** kept on the aims described above, the app uses a simple UI."

**Comment by JoseAlcerreca** [comment]
Thanks!

**Pull request merged**
