### PR TITLE
Add statistics use case

### PR DESCRIPTION
**Pull request by NikitaKozlov**
I built it using Gradle 2.1.0 , because “2.1.0-rc1” is incompatible with my Android Studio.

### CODE REVIEW

**Comment by flipper83** [comment]
👍 thank you!!

**Comment by JoseAlcerreca** [comment]
Thanks Kaerdan,

We kept `Task.java` in `data/` for consistency with todo-mvp but since you added another model, can you please move it to `statististics/domain/model` and move `Task.java` to `tasks/domain/model`?

**Comment by Kaerdan** [comment]
Done.
I have a small related question, why it was decided not to extract `domain` into separate package? I think it can help to understand app architecture.

**Comment by JoseAlcerreca** [comment]
Looks good to me! @flipper83?

**Comment by flipper83** [comment]
👍 good to me!

**Comment by JoseAlcerreca** [comment]
prod was broken in this PR. Fixed in #122

**Pull request merged**
