### PR TITLE
Add cancellation support to running UseCase

### PR DESCRIPTION
**Pull request by gokhanbarisaker**
This commits clones RxJava 1.x subscription logic in its most basic form.

Fix: #154, #155

### CODE REVIEW

**Comment by gokhanbarisaker** [comment]
Removed a personal TODO note as a fixup at `c65a66d`. Squashed commit with fixup to `c7cfe75` and updated pull request

**Comment by gokhanbarisaker** [comment]
hi @flipper83. Is it possible for you to review this?

**Comment by flipper83** [comment]
@gokhanbarisaker yes, I will try to review between this night and tomorrow morning.

**Comment by flipper83** [comment]
@gokhanbarisaker sorry for delay in my responses but I had been really full of work. I going to review right now and I will send you some comments

**Comment by flipper83** [comment]
After reviewing the code, some comments about this approach: For me this is overengineering the problem, you only create a subscription because you can have a memory leak in the uses cases, but you leak the architecture moving this problem to the user domain. This is not good because thread management is an implementation detail and we can fix it with another approach.

This problem doesn't need a reactive approach because you only have one response to each call, don't need a subscription that only has one response, it increases the difficulty of the domain calls, adding features that you don't use. Using an approach similar a Promises could be a better option.

On moving the code from inheritance to interfaces. You can create a lot of duplicate code, and move some dependencies from constructor to method, this will create problems with testing, or try to move it to DI approach. 

I going to write an example for fix the problem without move the cancelled to the user, and I show you.

**Comment by JoseAlcerreca** [comment]
@flipper83 can we close this?

**Comment by flipper83** [comment]
No yet please, I'm finishing an alternative, and I want write here the response. Sorry.

**Comment by JoseAlcerreca** [comment]
Great!

**Pull request closed without merging**
